blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogDetailView


app_name = BlogConfig.name

urlpatterns = [
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import NewsletterListView, NewsletterCreateView, NewsletterDetailView, NewsletterUpdateView, \
    NewsletterDeleteView, ManagerNewsletterListView, MailListView, MailCreateView, MailUpdateView, MailDeleteView, \
    AttemptListView, index_data

app_name = MailingConfig.name

urlpatterns = [
    path('', index_data, name='home'),
    path('list/', NewsletterListView.as_view(), name='list'),
    path('create/', cache_page(60)(NewsletterCreateView.as_view()), name='create'),
    path('detail/<int:pk>/', NewsletterDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', NewsletterUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', NewsletterDeleteView.as_view(), name='delete'),
    path('manager_list/', ManagerNewsletterListView.as_view(), name='manager_list'),

    path('message_list/', MailListView.as_view(), name='message_list'),
    path('message_create/', MailCreateView.as_view(), name='message_create'),
    path('message_edit/<int:pk>/', MailUpdateView.as_view(), name='message_edit'),
    path('message_delete/<int:pk>/', MailDeleteView.as_view(), name='message_delete'),

    path('logs_list/', AttemptListView.as_view(), name='logs_list'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserListView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>/', email_verification, name='email_confirm'),
    path('list/', UserListView.as_view(), name='list'),
    path('edit/<int:pk>/', UserUpdateView.as_view(), name='edit'),
]

mailing/models.py
from django.db import models
from django.utils import timezone

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='Адрес электронной почты')
    name = models.CharField(max_length=100, verbose_name='Имя клиента')
    comment = models.TextField(verbose_name='Комментарий клиента', **NULLABLE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return f' Клиент: {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mail(models.Model):
    subject = models.CharField(max_length=100, verbose_name='Тема письма')
    content = models.TextField(verbose_name='Содержание письма')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение рассылки'
        verbose_name_plural = 'Сообщения рассылки'


class Newsletter(models.Model):

    title = models.CharField(max_length=100, verbose_name='Название рассылки', **NULLABLE, default='Без названия')
    start_time = models.DateTimeField(default=timezone.now, verbose_name='начало рассылки')
    periodicity = (
        ('per_day', 'раз в день'),
        ('per_week', 'раз в неделю'),
        ('per_month', 'раз в месяц')
    )
    mail_status = (
        ('active', 'Создана'),
        ('send', 'Запущена'),
        ('ended', 'Завершена')
    )
    interval = models.CharField(max_length=25, choices=periodicity, default='per_week', verbose_name='Периодичность')
    status = models.CharField(max_length=25, choices=mail_status, default='active', verbose_name='Статус рассылки')
    mail = models.ForeignKey(Mail, on_delete=models.CASCADE, verbose_name='Сообщение рассылки')
    client = models.ManyToManyField(Client, verbose_name='Клиент')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions =[
            ('change_newsletter_status', 'Может менять статус рассылок'),
            ('view_newsletter_details', 'Может просматривать детали рассылок'),
            ('can_users_out', 'Может отключать пользователей'),
            ('view_newsletter_users', 'Может просматривать пользователей'),
        ]


class Attempt(models.Model):
    last_attempt_date = models.DateTimeField(auto_now=True, verbose_name='Дата последней попытки', **NULLABLE)
    attempt_status = models.BooleanField(default=False, verbose_name='статус')
    attempt_response = models.CharField(max_length=250, verbose_name='ответ почтового сервиса', **NULLABLE)
    newsletter = models.ForeignKey(Newsletter, on_delete=models.CASCADE, verbose_name='Рассылка')

    def __str__(self):
        return f'''Попытка отправки рассылки {self.newsletter.title} от {self.last_attempt_date}
    Статус: {self.attempt_status}
    Ответ сервера: {self.attempt_response}
    Состояние рассылки: {self.newsletter.status}'''

    class Meta:
        verbose_name = 'Попытка отправки рассылки'
        verbose_name_plural = 'Попытки отправки рассылки'

mailing/forms.py
from django.forms import ModelForm

from mailing.models import Newsletter


class NewsletterForm(ModelForm):
    class Meta:
        model = Newsletter
        exclude = ('user',)


class NewsletterManagerForm(ModelForm):
    class Meta:
        model = Newsletter
        fields = ('status',)

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse

from blog.models import Blog
from mailing.forms import NewsletterForm, NewsletterManagerForm
from mailing.models import Newsletter, Attempt, Mail, Client


class NewsletterListView(ListView):
    model = Newsletter


class ManagerNewsletterListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = 'mailing.view_mailingparameters'
    model = Newsletter
    template_name = 'mailing_parameters_list.html'


class NewsletterDetailView(LoginRequiredMixin, DetailView):
    model = Newsletter


class NewsletterCreateView(LoginRequiredMixin, CreateView):
    model = Newsletter
    fields = ['title', 'mail', 'start_time', 'interval', 'status', 'client']
    success_url = reverse_lazy('mailing:home')

    def form_valid(self, form):
        m_ps = form.save()
        m_ps.creator = self.request.user
        m_ps.save()
        return super().form_valid(form)


class NewsletterUpdateView(LoginRequiredMixin, UpdateView):
    model = Newsletter
    fields = ['name', 'mail', 'start_time', 'interval', 'status', 'client']
    success_url = reverse_lazy('mailing:list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.creator:
            return NewsletterForm
        if user.has_perm('mailing.change_status'):
            return NewsletterManagerForm
        raise PermissionDenied


class NewsletterDeleteView(LoginRequiredMixin, DeleteView):
    model = Newsletter
    success_url = reverse_lazy('mailing:list')


class MailListView(LoginRequiredMixin, ListView):
    model = Mail

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(creator=self.request.user)
        return qs


class MailCreateView(LoginRequiredMixin, CreateView):
    model = Mail
    fields = ['subject', 'content', ]
    success_url = reverse_lazy('mailing:create')

    def form_valid(self, form):
        message = form.save()
        message.creator = self.request.user
        message.save()
        return super().form_valid(form)


class MailUpdateView(LoginRequiredMixin, UpdateView):
    model = Mail
    fields = ['subject', 'content', ]
    success_url = reverse_lazy('mailing:message_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.creator:
            return NewsletterForm
        raise PermissionDenied


class MailDeleteView(LoginRequiredMixin, DeleteView):
    model = Mail
    success_url = reverse_lazy('mailing:message_list')


class AttemptListView(LoginRequiredMixin, ListView):
    model = Attempt


def index_data(request):
    count_mailing_items = Newsletter.objects.count()
    count_active_mailing_items = Newsletter.objects.filter(status='is_active').count()
    count_unic_clients = Client.objects.values_list('email', flat=True).count()
    random_blogs = Blog.objects.order_by('?')[:3]
    context = {'count_mailing_items': count_mailing_items,
               'count_active_mailing_items': count_active_mailing_items,
               'count_unic_clients': count_unic_clients,
               'random_blogs': random_blogs,
               }

    return render(request, 'mailing/newsletter_list.html', context)

mailing/templates/mailing/attempt_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="mb-3">

</div>

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">


    {% for object in object_list %}

    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.last_attempt_date }}</h4>
            </div>
            <div class="card-body">

                <ul class="list-unstyled mt-3 mb-4">
                    <li>Статус: {{ object.attempt_status }}</li>
                </ul>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Ответ сервера: {{ object.attempt_response }}</li>
                </ul>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Рассылка: {{ object.newsletter }}</li>
                </ul>



            </div>


        </div>
    </div>

    {% endfor%}
</div>
{% endblock %}

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <title>Печкин</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/offcanvas-navbar.css' %}" rel="stylesheet">
</head>
{% block content %}
{% endblock %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

<script src="{% static 'js/offcanvas-navbar.js' %}"></script>
</html>

mailing/templates/mailing/mail_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="text-center">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Хотие удаленить эту рассылку ?</h4>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
                <li>Название: {{ object.title }}</li>
                <li>Содержимое сообщения: {{ object.content }}</li>
            </ul>
        </div>
        <div class="card-footer">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="w-100 btn btn-lg btn-outline-danger mb-2">Да</button>
                <a href="{% url 'mailing:message_list' %}" class="w-100 btn btn-lg btn-outline-success ">Нет</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mail_form.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3 text-center">

            <h4 class="my-0 fw-normal">Сообщение</h4>


        </div>
        <div class="card-body">

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Принять</button>
            </form>


        </div>
        <div class="card-footer">
             <a href="{% url 'mailing:create' %}" class="w-100 btn btn-lg btn-outline-primary">Отмена</a>
        </div>
    </div>
</div>


{% endblock %}

mailing/templates/mailing/mail_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="mb-3">
    <a href="{% url 'mailing:message_create' %}" class="w-100 btn btn-lg btn-outline-primary">Создать сообщение</a>
</div>

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">


    {% for object in object_list %}

    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.subject }}</h4>
            </div>
            <div class="card-body">

                <ul class="list-unstyled mt-3 mb-4">
                    <li>Текст сообщения: {{ object.content }}</li>

                </ul>
                <a href="{% url 'mailing:message_edit'  object.pk %}" type="button"
                   class="w-100 btn btn-lg btn-outline-primary">Редактировать</a>


            </div>
            <div class="card-footer">
                <a href="{% url 'mailing:message_delete'  object.pk %}" type="button"
                   class="w-100 btn btn-lg btn-outline-primary">Удалить</a>
            </div>

        </div>
    </div>

    {% endfor%}
</div>
{% endblock %}

mailing/templates/mailing/newsletter_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}


<div class="text-center">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Хотие удаленить эту рассылку ?</h4>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
                <li>Название: {{ object.title }}</li>
                <li>Старт рассылки: {{ object.start_time }}</li>
                <li>Интервал: {{ object.interval }}</li>
            </ul>
        </div>
        <div class="card-footer">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="w-100 btn btn-lg btn-outline-danger mb-2">Ок</button>
                <a href="{% url 'mailing:list' %}" class="w-100 btn btn-lg btn-outline-success ">No</a>
            </form>
        </div>

    </div>
</div>


{% endblock %}

mailing/templates/mailing/newsletter_detail.html
{% extends 'mailing/base.html' %}

{% block content %}



<div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3 text-center">
            <h4 class="my-0 fw-normal">{{ object.title }}</h4>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
                <li>Старт рассылки: {{ object.start_time }}</li>
                <li>Интервал: {{ object.interval }}</li>
                <li>Текст письма: {{ object.mail.subject }}</li>
                <li>Содержимое письма: {{ object.mail.content }}</li>
                <li>Клиенты: {% for client in object.client.all %} {{client.email}} {% endfor %}</li>
            </ul>


            

            <a href="{% url 'mailing:edit' object.pk %}" type="button" class="w-100 btn btn-lg btn-outline-primary">Редактировать</a>
        </div>
    </div>
</div>



{% endblock %}

mailing/templates/mailing/newsletter_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="mb-3">
    <a href="{% url 'mailing:message_create' %}" class="w-100 btn btn-lg btn-outline-primary">Создать сообщение</a>
</div>

<div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3 text-center">
            {% if object %}
            <h4 class="my-0 fw-normal">{{ object.title }}</h4>
            {% else %}
            <h4 class="my-0 fw-normal">Создание рассылки</h4>
            {% endif%}

        </div>
        <div class="card-body">

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Принять</button>
            </form>


        </div>
        <div class="card-footer">
            <a href="{% url 'mailing:list' %}" class="w-100 btn btn-lg btn-outline-primary">Отмена</a>
        </div>
    </div>
</div>


{% endblock %}

mailing/templates/mailing/newsletter_list.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <title>Печкин</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/offcanvas-navbar.css' %}" rel="stylesheet">
</head>
{% block content %}
<body class="bg-body-tertiary">
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>


<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
    <div class="container-fluid">
        <h1 class="navbar-brand">Печкин</h1>
        <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'mailing:create' %}">Создать рассылку</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="nav-scroller bg-body shadow-sm">
    <nav class="nav" aria-label="Secondary navigation">
        <h3 class="nav-link">
            Количество рассылок :
            <span class="badge text-bg-light rounded-pill align-text-bottom">{{ count_mailing_items  }}</span>
        </h3>
        <h3 class="nav-link">
            Количество активных рассылок :
            <span class="badge text-bg-light rounded-pill align-text-bottom">{{ count_active_mailing_items }}</span>
        </h3>
        <h3 class="nav-link">
            Количество уникальных клиентов для рассылок :
            <span class="badge text-bg-light rounded-pill align-text-bottom">{{ count_unic_clients }}</span>
        </h3>
    </nav>
</div>

<main class="container">
    <div class="d-flex align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
        <div class="lh-1">
            <h2 class="h2 mb-0 text-white lh-1">Печкин</h2>
            <small>Сервис для отправки рассылок.</small>
        </div>
    </div>

    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <h4 class="border-bottom pb-2 mb-0">Блог</h4>
        <div class="d-flex text-body-secondary pt-3">
            {% for object in random_blogs %}
            <p class="pb-3 mb-0 small lh-sm border-bottom">

                <strong class="d-block text-gray-dark">{{ object.title}}</strong>
                {{ object.text }}
            </p>
        </div>

        {% endfor %}
    </div>

</main>
</body>
{% endblock %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

<script src="{% static 'js/offcanvas-navbar.js' %}"></script>

</html>